# -*- coding: utf-8 -*-
"""OCR_Python_Tesseract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzJBqUUq65H3hu8i6gBAvDGsjOPvgy14

# OCR com Python Tesseract

Este notebook explora o Reconhecimento Óptico de Caracteres (OCR) utilizando o módulo `pytesseract` em conjunto com a *engine* Tesseract. Ele aborda diversas etapas e técnicas para a extração de texto de imagens:

*   **Instalação e Configuração:** realiza a instalação do Tesseract-OCR e `pytesseract`, além de instalar também o pacote para a linguagem em português.
*   **Extração de Texto de Imagens Locais e Online:** demonstra como extrair texto tanto de arquivos de imagem armazenados localmente quanto de imagens acessadas diretamente da Internet.
*   **Impacto do Tamanho da Imagem:** analisa como o tamanho da fonte pode afetar a precisão do reconhecimento de texto.
*   **Pré-processamento para Melhorar OCR:** apresenta técnicas de pré-processamento de imagens, como conversão para escala de cinza, aplicação de filtros para remoção de ruídos com OpenCV e redimensionamento, para otimizar a qualidade da extração.
*   **Configurações Avançadas do Tesseract:** explora o uso de configurações específicas do Tesseract, como *whitelist* (para restringir caracteres) e *Page Segmentation Mode* (PSM), para casos de uso como reconhecimento de placas de carro e códigos de barras.

## Instalação e Descompactação do Arquivo de Imagens

Nesta seção são instalados o motor Tesseract com o pacote para a linguagem em português e o módulo pytesseract. Também é descompactado o arquivo com as imagens (`imagens.zip`) para uso nas próximas etapas.

Logo, faça primeiro o upload do arquivo `imagens.zip` no sistema de arquivos e depois execute a célula abaixo.
"""

"""
!apt update
!apt install tesseract-ocr tesseract-ocr-por
!pip install pytesseract
"""
import zipfile
import os

arquivo_imagens = 'imagens.zip'
if not os.path.exists(arquivo_imagens):
  print(f'Arquivo {arquivo_imagens} não encontrado! Faça o upload do arquivo primeiro.')
else:
  # Descompactar arquivo
  try:
    with zipfile.ZipFile(arquivo_imagens, 'r') as zip:
      zip.extractall()

  except Exception as e:
    print(f'Erro ao descompactar {arquivo_imagens}')

"""## Extração de Texto de Imagens Locais

Nesta seção é demonstrado como extrair texto de imagens armazenadas localmente, utilizando o `pytesseract` para reconhecimento óptico de caracteres.
"""

import pytesseract
from PIL import Image

# Abrir a imagem
imagem = Image.open('imagem_com_texto_eng.png')

# Extrair texto
texto = pytesseract.image_to_string(imagem)

# Mostrar a imagem e o texto extraído
display(imagem)
print('\nTexto extraído:')
print(texto)

# Abrir uma nova imagem
imagem_eng = Image.open('imagem_com_texto_por.png')

# Mostrar a imagem
display(imagem_eng)

# Extrair texto
texto_eng = pytesseract.image_to_string(imagem_eng)

print('\nTexto extraído com configuração default (inglês):')
print(texto_eng)

# Extrair texto com linguagem especificada em português
texto_por = pytesseract.image_to_string(imagem_eng, lang='por')

print('Texto extraído com configuração de linguagem em português:')
print(texto_por)

"""## Extração de Texto de Imagens Online

Nesta seção vamos observar como extrair texto de imagens acessadas diretamente da Internet, utilizando `pytesseract` em conjunto com o módulo `requests`.
"""

import pytesseract
from PIL import Image
import requests
from io import BytesIO

url_imagem = 'https://raw.githubusercontent.com/madmaze/pytesseract/refs/heads/master/tests/data/test.png'

headers = {
    'User-Agent': 'ExampleRPA/1.0'
}

# Acesso à imagem com o método GET
try:
  resposta = requests.get(url_imagem, headers=headers)

except requests.exceptions.Timeout:
  print('Timeout! O servidor demorou muito para responder.')
except requests.exceptions.ConnectionError:
  print('Não foi possível conectar à página Web. Verifique se possui conexão com a Internet.')

if resposta.status_code == 200:
  # Realiza a conversão da resposta para a imagem
  imagem = Image.open(BytesIO(resposta.content))

  # Mostrar a imagem
  display(imagem)

  # Extrair texto
  texto = pytesseract.image_to_string(imagem)

  print('\nTexto extraído da imagem online:')
  print(texto)
else:
  print(f'Erro HTTP com código {resposta.status_code}')

"""## Extração de Texto de Imagens com Tamanhos Diferentes

Nesta seção visualizamos como o tamanho da fonte  pode impactar o reconhecimento de texto pelo `pytesseract`.
"""

import pytesseract
from PIL import Image

# Abrir a imagem com texto pequeno
imagem = Image.open('imagem_com_texto_pequeno.png')

# Mostrar a imagem
display(imagem)

# Extrair texto
texto = pytesseract.image_to_string(imagem, lang='por')

print('\nTexto extraído:')
print(texto)

# Abrir a imagem com texto grande
imagem_nova = Image.open('imagem_com_texto_grande.png')

# Mostrar a imagem
display(imagem_nova)

# Extrair texto
texto_nova = pytesseract.image_to_string(imagem_nova, lang='por')

print('\nTexto extraído:')
print(texto_nova)

"""## Pré-processamento para Melhorar OCR

Nesta seção vamos aprender como técnicas de pré-processamento de imagens podem melhorar a precisão do OCR. Começamos com uma extração de texto sem pré-processamento para demonstrar os desafios de imagens de baixa qualidade.

Em seguida, vamos aplicar uma série de passos de pré-processamento, incluindo:

1.  **Conversão para escala de cinza**: reduz a complexidade da imagem, mantendo a informação de luminância para o OCR.
2.  **Filtros de remoção de ruídos (OpenCV)**: suavização da imagem com o filtro da mediana para remover ruídos que podem confundir o Tesseract.
3.  **Redimensionamento**: aumento da resolução da imagem para ajudar o Tesseract a detectar caracteres pequenos ou de baixa qualidade.

O objetivo é mostrar o impacto positivo de cada etapa na qualidade do texto extraído.
"""

import pytesseract
from PIL import Image, ImageEnhance, ImageFilter
import numpy as np
import cv2

#############################################
# Extrair texto sem pré-processamento
#############################################

# Abrir a imagem com texto pequeno
imagem = Image.open('documento_problemas.jpg')

# Mostrar a imagem
display(imagem)

# Extrair texto
texto = pytesseract.image_to_string(imagem, lang='por')

print('\nTexto extraído sem pré-processamento:')
print(texto)

#############################################
# Extrair texto com pré-processamento
#############################################

# Conversão para a escala de cinza
imagem_cinza = imagem.convert('L')
display(imagem_cinza)

texto = pytesseract.image_to_string(imagem_cinza, lang='por')
print('\nTexto extraído após escala de cinza:')
print(texto)

# Filtros do OpenCV para remoção dos ruídos
imagem_cv = np.array(imagem_cinza)

# Filtro de mediana com blur suave
imagem_cv_filtro = cv2.medianBlur(imagem_cv, 3)

# Converte novamente para PIL
imagem_filtro = Image.fromarray(imagem_cv_filtro)
display(imagem_filtro)

texto = pytesseract.image_to_string(imagem_filtro, lang='por')
print('\nTexto extraído após filtro:')
print(texto)

# Redimensionamento
largura, altura = imagem_filtro.size
imagem_grande = imagem_filtro.resize((largura*2, altura*2), Image.Resampling.LANCZOS)
display(imagem_grande)

texto = pytesseract.image_to_string(imagem_grande, lang='por')
print('\nTexto extraído após pré-processamento:')
print(texto)

"""## Configurações do Tesseract

Nesta seção vamos aplicar configurações específicas do Tesseract para reconhecer uma placa de carro e uma imagem com um código de barras e seu respectivo código numérico.

O Tesseract possui duas funcionalidades que podem afetar o resultado do OCR, o *whitelist* e o *Page Segmentation Mode* (PSM). Seu uso correto pode auxiliar na acurácia do OCR.

O *whitelist* determina quais caracteres são esperados para a detecção. Os usos mais comuns de *whitelist* são:

* `ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`: letras maiúsculas e números
* `0123456789`: apenas números
* `0123456789.-/`: números com separadores, usado para CPF, telefone e datas
* `0123456789,.R$`: valores monetários

Já o PSM determina como a *engine* de OCR deve interpretar a estrutura da página, ou seja, como ele deve dividir a imagem em blocos, linhas, palavras ou caracteres antes de tentar reconhecer o texto. Os modos mais comuns são:

* `--psm 3`: segmentação totalmente automática
* `--psm 6`: bloco de texto uniforme
* `--psm 7`: única linha
* `--psm 8`: única palavra
* `--psm 13`: linha de texto simples (mais específico para linhas individuais)

"""

import pytesseract
from PIL import Image

# Abrir a imagem com placa de carro
imagem_placa = Image.open('placa_carro.png')

# Mostrar a imagem
display(imagem_placa)

# Exemplo: extrair apenas números e letras maiúsculas
config_placa = '-c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 --psm 8'
texto_placa = pytesseract.image_to_string(imagem_placa, config=config_placa)
print("\nIdentificação da placa:")
print(texto_placa)

# Abrir a imagem com código de barras
imagem_codigo = Image.open('codigo_barras.png')

# Mostrar a imagem
display(imagem_codigo)

# Exemplo: extrair apenas números
config_codigo = '-c tessedit_char_whitelist=0123456789 --psm 6'
texto_codigo = pytesseract.image_to_string(imagem_codigo, config=config_codigo)
print("\nIdentificação de código de barras:")
print(texto_codigo)

# Recorte da imagem para eliminar o texto que não interessa
largura, altura = imagem_codigo.size
imagem_codigo_recorte = imagem_codigo.crop((0, 0, largura, altura*0.8))

# Mostrar a imagem recortada
display(imagem_codigo_recorte)

# Exemplo: extrair apenas números
texto_codigo_recorte = pytesseract.image_to_string(imagem_codigo_recorte, config=config_codigo)
print("\nIdentificação de código de barras após o recorte:")
print(texto_codigo_recorte)