# -*- coding: utf-8 -*-
"""Logging Automatically generated by Colab.
# Logging
Este notebook explora o uso de logging em Python, começando com exemplos básicos de funções com e sem logging para depuração. Em seguida, demonstra como configurar o logging para salvar informações em um arquivo. Por fim, apresenta uma atividade que envolve a manipulação de arquivos CSV (leitura, filtragem e ordenação de dados) para que o logging possa ser adicionado.
Exemplo de implementação da função fatorial. Relembrando, fatorial é calculado como n! = n\*n-1\*(n-2)\*...\*3\*2\*1.

Função fatorial com erro.
"""

def factorial(n):
    total = 1
    for i in range(n + 1):
        total *= i
    return total

print(factorial(10))

"""Função fatorial com erro, mas com o logging."""

import logging
import sys

# Remove handlers antigos se existirem, para funcionar no Google Colab
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    datefmt='%d/%m/%Y %H:%M:%S')

def factorial(n):
    logging.debug('Início do fatorial(' + str(n) + ')')
    total = 1
    for i in range(1, n + 1):
        total *= i
        logging.debug('i = ' + str(i) + ', total = ' + str(total))
    logging.debug('Fim do fatorial(' + str(n) + ')')
    return total

logging.info("Aplicação iniciada com sucesso.")
print(factorial(5))
logging.info('Aplicação finalizada!')

"""Uso de logging, salvando log em arquivo."""

import logging
import sys

# Remove handlers antigos se existirem, para funcionar no Google Colab
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(filename='divisao.log',
                    level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    datefmt='%d/%m/%Y %H:%M:%S')


def dividir_numeros(a, b):
    """
    Função que divide dois números e demonstra a diferença
    entre error e exception
    """
    logging.debug(f'Início da divisão: {a} / {b}')

    try:
        resultado = a / b
        logging.debug(f'Resultado calculado: {resultado}')
        return resultado

    except ZeroDivisionError:
        # Uso do logging.error
        logging.error(f"Tentativa de divisão por zero! Valores: a = {a}, b = {b}")
        return None

    except TypeError as e:
        # Uso do logging.exception
        logging.exception(f"Erro de tipo ao dividir {a} / {b}")
        return None

    except Exception as e:
        # Usando exception para erros inesperados
        logging.exception(f"Erro inesperado na divisão")
        return None

logging.info("Aplicação iniciada com sucesso.")
resultado = dividir_numeros(10, 2)
print(f"Resultado = {resultado}")
resultado = dividir_numeros(7, 0)
print(f"Resultado = {resultado}")
resultado = dividir_numeros('10', 2)
print(f"Resultado = {resultado}")
resultado = dividir_numeros(10, None)
print(f"Resultado = {resultado}")
logging.info('Aplicação finalizada!')

"""## Atividade: Adição do Logging Colaborativamente

Nesta atividade, vamos colaborar para adicionar logging ao código abaixo, que manipula arquivos CSV. O objetivo é registrar eventos importantes, como a leitura de arquivos, filtragem de dados, erros potenciais e o resultado final das operações.
"""

import csv
import logging


# Remove handlers antigos se existirem, para funcionar no Google Colab
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(filename='series.log',
                    level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    datefmt='%d/%m/%Y %H:%M:%S')

# Informações sobre séries para exemplificar um cadastro
series = [
    ['titulo', 'ano_lancamento', 'temporadas', 'nota_imdb', 'streaming', 'genero'],
    ['Stranger Things', '2016', '4', '8.7', 'Netflix', 'Ficção/Terror'],
    ['The Crown', '2016', '6', '8.6', 'Netflix', 'Drama Histórico'],
    ['Game of Thrones', '2011', '8', '9.2', 'HBO Max', 'Fantasia'],
    ['Breaking Bad', '2008', '5', '9.5', 'Netflix', 'Drama'],
    ['The Office', '2005', '9', '9.0', 'Prime Video', 'Comédia'],
    ['Dark', '2017', '3', '8.8', 'Netflix', 'Ficção/Suspense'],
    ['Friends', '1994', '10', '8.9', 'HBO Max', 'Comédia'],
    ['Black Mirror', '2011', '5', '8.8', 'Netflix', 'Ficção/Drama'],
    ['The Boys', '2019', '3', '8.7', 'Prime Video', 'Ação/Comédia'],
    ['Love, Death & Robots', '2019', '3', '8.4', 'Netflix', 'Animação/Ficção'],
]
logging.info("Aplicação iniciada com sucesso.")
# Criação de um arquivo CSV
# O uso de newline='' evita que sejam adicionadas linhas em branco no Windows
try:
  logging.debug(f'Abertura do arquivo')
  with open('series.csv', 'w', newline='', encoding='utf-8') as arquivo:
      escritor = csv.writer(arquivo)
      escritor.writerows(series)
      logging.debug(f'Abertura do arquivo com sucesso')
except Exception as e:
    logging.error(f'Abertura do arquivo com falha')
    raise

# Leitura com csv.DictReader() e escrita com csv.DictWriter()
try:
    logging.debug(f'Início da leitura do arquivo')
    with open('series.csv', 'r', encoding='utf-8') as arquivo:
        leitor = csv.DictReader(arquivo)

        # Criação de uma nova lista para armazenar apenas séries de Ficção
        series_ficcao = []

        for idx, serie in enumerate(leitor, start=1):
            # Selecionar o gênero Ficção
            if 'Ficção' in serie['genero']:
                logging.debug(f'Abertura do arquivo')
                series_ficcao.append(serie)

        # Ordenar séries de Ficção por notas do imdb de forma decrescente
        series_ficcao_ordenadas = sorted(series_ficcao,
                                         key=lambda x: float(x['nota_imdb']),
                                         reverse=True)

        # Escrita com csv.DictWriter()
        with open('series_ficcao_ordenada.csv', 'w', newline='', encoding='utf-8') as novo_arquivo:
            escritor = csv.DictWriter(novo_arquivo, fieldnames=leitor.fieldnames)
            escritor.writeheader()

            for idx, serie in enumerate(series_ficcao_ordenadas, start=1):
                escritor.writerow(serie)

except FileNotFoundError as e:
    raise logging.exception(f"Arquivo não encontrado: {e}")
except KeyError as e:
    raise logging.exception(f"Arquivo não encontrado: {e}")
except Exception as e:
    raise


print('Gerado arquivo series_ficcao_ordenada.csv com as séries de ficção ordenadas pela nota do imdb.')
logging.info('Aplicação finalizada!')